name: sysfoo-ci
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello sysfoo-ci!"
        
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Test
        run: mvn test
        
      - name: Clean package
        run: mvn clean
        
      - name: Create Package
        run: mvn package 

      - name: View package
        run: ls -lrt target
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Sysfoo
          path: target/**.war
 

      
